# version: '3.8'

# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     container_name: jenkins
#     privileged: true
#     user: root
#     ports:
#       - "8080:8080"
#       - "50000:50000"
#     volumes:
#       - jenkins_data:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /usr/bin/docker:/usr/bin/docker
#     environment:
#       - DOCKER_HOST=unix:///var/run/docker.sock

# volumes:
#   jenkins_data:

version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-plugins.txt:/usr/share/jenkins/ref/plugins.txt
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins-net

volumes:
  jenkins_data:

networks:
  jenkins-net:
    driver: bridge