version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always   # ğŸ”¥ RedÃ©marre Ã  chaque reboot automatiquement
    user: root        # ğŸ”¥ Assure que Docker CLI marche toujours
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # ğŸ”¥ Jenkins parle au Docker host

volumes:
  jenkins_home:
